version: "3"
services:
  php-fpm:
    container_name: php-fpm
    image: "${DOCKER_USER}/php-fpm:7.2.5"
    build:
      context: ${DOCKERFILE_DIR}/php72
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:    
        - ${DOCKERFILE_DIR}/php72/etc:/usr/local/etc
        - ${DOCKER_LOGS_DIR}/php72:/var/log/php
        - ${WEBROOT_DIR}:/var/www/html
  nginx:
    container_name: nginx
    image: "${DOCKER_USER}/nginx:1.11"
    build:
      context: ${DOCKERFILE_DIR}/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKERFILE_DIR}/nginx/conf/conf.d:/etc/nginx/conf.d
      - ${DOCKERFILE_DIR}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_LOGS_DIR}/nginx:/var/log/nginx
      - ${WEBROOT_DIR}:/var/www/html
    links:
      - php-fpm
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ${DOCKERFILE_DIR}/mysql57/conf:/etc/mysql/conf.d
        - ${DOCKER_LOGS_DIR}/mysql57:/logs
        - ${DOCKER_DATA_DIR}/mysql57:/var/lib/mysql
  redis:
    image: redis:5.0
    container_name: redis-server
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKERFILE_DIR}/redis50/conf/redis.conf:/etc/redis/redis.conf
      - ${DOCKERFILE_DIR}/redis50/data:/data
    command: ['redis-server', '/etc/redis/redis.conf']