version: "3"
services:
  php-fpm:
    container_name: php-fpm
    image: "${DOCKER_USER}/php-fpm:7.2.5"
    build:
      context: ${DOCKERFILE_DIR}/php7.2
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:    
        - ${DOCKER_DIR}/php7.2/etc:/usr/local/etc
        - ${DOCKER_DIR}/php7.2/logs:/var/log/php
        - ${WEBROOT_DIR}:/var/www/html
  nginx:
    container_name: nginx
    image: "${DOCKER_USER}/nginx:1.11"
    build:
      context: ${DOCKERFILE_DIR}/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKER_DIR}/nginx/conf.d:/etc/nginx/conf.d
      #- ${DOCKER_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_DIR}/nginx/logs:/var/log/nginx
      - ${WEBROOT_DIR}:/var/www/html
    links:
      - php-fpm
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ${DOCKER_DIR}/mysql5.7/conf:/etc/mysql/conf.d
        - ${DOCKER_DIR}/mysql5.7/logs:/logs
        - ${DOCKER_DIR}/mysql5.7/data:/var/lib/mysql
  redis:
    image: redis:5.0
    container_name: redis-server
    ports:
      - 6379:6379
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ${DOCKER_DIR}/redis/conf:/usr/local/etc/redis
      - ${DOCKER_DIR}/redis/data:/data
